### ISSUE TITLE
Narrow non-breaking option for dewidowing appears to not work

### ISSUE THREAD

**Issue by nternetinspired** [nystudio107/craft3-typogrify#10]
Hi Andrew 👋 

It may be possible that I've not configured it correctly but the option to set narrow non-breaking space characters when dewidowing appears to not work.

I've tried setting the option https://github.com/nystudio107/craft-typogrify/blob/v1/src/config.php#L163 to true in both this file and in /config/typogrify and neither seem to have any effect.

Craft 3.0.8, Craft Typogrify 1.1.10.

Regards,

Seth

**Comment by khalwat** [comment]
Hrm. I'm not sure, it might be an issue with the PhpTypography layer that it's using? I looked through their code a bit, and it seems like it should be working. Maybe ask here? 

https://github.com/mundschenk-at/php-typography
