### ISSUE TITLE
Widow prevention setting nbsp between 2nd and 3rd to last words.

### ISSUE THREAD

**Issue by wfendler** [nystudio107/craft3-typogrify#11]
I would expect the `&nbsp;` to be between the last and second to last word. Perhaps there's some configuration I could tweak? I've looked through the file but don't see anything.

Thanks for any help!

**Comment by khalwat** [comment]
That's where it should be, yes. There are a number of config settings related to Widows that you can tweak:

https://github.com/nystudio107/craft-typogrify/blob/v1/src/config.php#L165

**Comment by wfendler** [comment]
Hm, I didn't change any settings but the nbsp was in the second to last gap not the last. Site-wide. I will investigate further.
