### ISSUE TITLE
Try to avoid unescaped content

### ISSUE THREAD

**Issue by codyjames** [nystudio107/craft3-typogrify#15]
When using Typogrify in tandem with the translation filter we ran into a little issue.

This allowed unescaped content (not desired): 
```{{ 'Search for: "{query}"'|t({ query: query })|typogrify }}```

While this did not:
```{{ 'Search for: "{query}"'|t({ query: query }) }}```

So we had to adjust to this:
```{{ 'Search for: "{query}"'|t({ query: query|escape })|typogrify }}```

Is this something that this plugin can help with?

More info here: https://github.com/craftcms/cms/issues/2162#issuecomment-427105519

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-typogrify/commit/df21158ae58771ac89d8f723ffa1c05ee372cfc7

**Comment by codyjames** [comment]
Wow, that was fast. Thanks!
