### ISSUE TITLE
v1.1.12 prints the raw HTML to the browser

### ISSUE THREAD

**Issue by sjenset** [nystudio107/craft3-typogrify#16]
I have the following TWIG-code in my template:

`<h1 class="entry__title" data-dynamic-font-size>{{ entry.title|typogrify(true) }}</h1>`

In v1.1.11 it outputs as such (when viewed in the browser):
![image](https://user-images.githubusercontent.com/12337525/46530822-4bae4b80-c89b-11e8-9809-5dc05b77ef42.png)

However, in v1.1.12 it outputs as such:
![image](https://user-images.githubusercontent.com/12337525/46530925-aa73c500-c89b-11e8-8f7b-2ca76d292dcb.png)

The only thing that has changed in the project is the tyopgrify version, and it can be reproduced by alternating between v1.1.11 and v1.1.12 consitently.

**Comment by khalwat** [comment]
Thanks, this is a regression, I will address it.

**Comment by khalwat** [comment]
Fixed in 1.1.13: https://github.com/nystudio107/craft-typogrify/releases/tag/1.1.13
