### ISSUE TITLE
Text doesn't look good on iOS

### ISSUE THREAD

**Issue by fdelaneau** [nystudio107/craft3-typogrify#19]
On Safari iOS the kerning is completely off while everything looks fine on Safari macOs.

Here is a screenshot on iOS : https://cl.ly/8694836c4548

**Comment by khalwat** [comment]
Have you tried disabling the hyphenation? I'm thinking that is what would be causing this to happen... @fdelaneau

**Comment by fdelaneau** [comment]
Sorry, I still didn't have time to check and answer your request. I’ll try to do that this weekend.
