### ISSUE TITLE
Pluralize/singularize not working

### ISSUE THREAD

**Issue by shornuk** [nystudio107/craft3-typogrify#20]
Tested with the latest version in a couple of sites.

Both filters just return a plurailized version regardless of the second number being passed in.

```
{% set numApples = 1 %}
{{ 'apple' |pluralize(numApples) }}

or 

{% set numApples = 1 %}
{{ craft.typogrify.pluralize('apple', numApples) }}
```

is actually outputting 'Apples'

**Comment by khalwat** [comment]
hrm. Will have a look, thanks!

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-typogrify/releases/tag/1.1.16
