### ISSUE TITLE
All versions of wordLimit add the ... even when not truncated

### ISSUE THREAD

**Issue by jmcgaha** [nystudio107/craft3-typogrify#23]
Switching to truncateOnWord fixed this temporarily

Craft 3.1.16
Typogrify 1.1.16

**Comment by jamesmacwhite** [comment]
I can also confirm this, here's a test case:

`Browse over 300 courses to find a career path that's right for you.` (13 words)

Apply a word limit value that's higher than the word count in the test case:

```{{ 'Browse over 300 courses to find a career path that's right for you.' |wordLimit(20) }}```

The output becomes:

`Browse over 300 courses to find a career path that's right for you....`

Given the word count of the test case is < 20, nothing should have been appended. This was observed on Craft 2 site that originally used the hacksaw plugin.

Hope that makes sense.

**Comment by khalwat** [comment]
fixed in https://github.com/nystudio107/craft-typogrify/commit/770939ba98604c1f8913a371a35ec4edd4777467
