### ISSUE TITLE
Strange bug: word disappears when set_dewidow_word_number is > 1

### ISSUE THREAD

**Issue by benface** [nystudio107/craft3-typogrify#24]
Simplest reproducible case:

1. Set the config setting `set_dewidow_word_number` to `2`
2. Put this in a template:
    ```
    {% filter typogrify %}
        <p>
            Test
        </p>
    {% endfilter %}
    ```
    (Note: the newlines matter; `<p>Test</p>` doesn't reproduce the issue)
3. Render the template. Notice the "Test" word is gone; the source reads: `<p></p>`

**Comment by khalwat** [comment]
This is probably an issue that should be reported on the underlying library -> https://github.com/mundschenk-at/php-typography

**Comment by benface** [comment]
Thank you, done here: mundschenk-at/php-typography/issues/106
