### ISSUE TITLE
Fix config comment

### ISSUE THREAD

**Issue by chrisrowe** [nystudio107/craft3-typogrify#26]
This should read `Enables/disables replacement of 1st with 1<sup>st</sup>. `

https://github.com/nystudio107/craft-typogrify/blob/4106b4469057508061f751c6b7b4460f12c6a1b1/src/config.php#L140

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-typogrify/commit/98a126ddcf74f8ee9529df92824e52e2bd99afb7
