### ISSUE TITLE
Typogrify bug: Words that look French incorrectly get accents etc.

### ISSUE THREAD

**Issue by ricricucit** [nystudio107/craft3-typogrify#31]
I'm gonna report, exactly (copy-paste) as a client of us reported: 

Typogrify is giving us a hard time by misidentifying certain English or German words as French and giving them accents - like on this page in the title and body text: https://bit.ly/2MMTqvk. The plug-in has changed "Blase" (German for bubble) into "Blasé" (French for bored or indifferent). Another example on this page, where the English "regime" got changed into "régime" (not as bad, but still not correct): https://bit.ly/2oOirhB

Is there a way to customize the plug-in so it doesn't apply the rule of automatically changing certain words into their French counterparts?

**Comment by ricricucit** [comment]
`ping`

**Comment by fthues** [comment]
`"set_smart_diacritics" => false`

**Comment by mundschenk-at** [comment]
@ricricucit, can you tell me which version of [`mundschenk-at/php-typography`](https://github.com/mundschenk-at/php-typography) and what settings were used in the installation producing `Blasé`? I'm trying to reproduce this in the underlying library (while `blase => blasé` is ambiguous for German and will be removed from the smart diacritics file for that language, the title-cased `Blase` should not have been touched.

**Comment by ricricucit** [comment]
`Typogrify 1.1.18` on `Craft 3.3.15`

**Comment by mundschenk-at** [comment]
> `Typogrify 1.1.18` on `Craft 3.3.15`

Yes, but I'd need the `php-typography` version installed as a dependency.

**Comment by ricricucit** [comment]
sorry. I cannot cehck this, I believe. Due to restriction of the client's (shared) hosting capabilities

**Comment by mundschenk-at** [comment]
You should be able to search for the package name in `composer.lock` if you have access to that.

**Comment by ricricucit** [comment]
right, good call :)

```
"name": "mundschenk-at/php-typography",
"version": "v6.5.1",
```

**Comment by mundschenk-at** [comment]
Thanks, that's almost current (and nothing relevant has changed). In that case, can you please post your settings (Typogrify's is OK, I'll try to derive the underlying PHP-Typography settings from that).

**Comment by ricricucit** [comment]
Sorry, I can't quite follow, the issue was from long time ago and I have to restart this project every time (and remember how things worked) 😛

...can help me, but telling me where to find the things you need? Thanks

**Comment by mundschenk-at** [comment]
Sorry, I don't know where the settings are located in Typogrify. I only maintain the `php-typography` package and have no clue about Craft.
