### ISSUE TITLE
Call from PHP?

### ISSUE THREAD

**Issue by ursbraem** [nystudio107/craft3-typogrify#32]
Is Typogrify only designed for use from Twig, or is it possible to call it (eg smartypants) directly from PHP (as in element api)? If so, can you give me a hint on the syntax?

**Comment by joshuabaker** [comment]
```php
use nystudio107\typogrify\Typogrify;

Typogrify::$plugin->typogrify->typogrify($text, $isTitle);
```

**Comment by ursbraem** [comment]
Thanks @joshuabaker !!

**Comment by joshuabaker** [comment]
@ursbraem If you’re set please can you close this. 😊
