### ISSUE TITLE
Strange &nbsp; display issues in heading tags

### ISSUE THREAD

**Issue by jdsimcoe** [nystudio107/craft3-typogrify#33]
Recently I have encountered two local Craft sites running in Laravel Valet that have developed a strange case of `&nbsp;` characters inserted after every character:

![image](https://user-images.githubusercontent.com/275617/69462835-eb909800-0d2e-11ea-997b-1e0c1a78c4f6.png)

In this case, it was inserted in an `<h2>` class. Any ideas on why this might be happening? Nothing has changed with my configuration or output.

Here is the snippet of code that is controlling this output:

```twig
<h2 class="font-weight-bold">
  {{ block.heading|nl2br|typogrify }}
</h2>
```

**Comment by msiemens** [comment]
For me, this issue started to occur when enabling PHP 7.3 and was fixed again when switching back to PHP 7.2

**Comment by msiemens** [comment]
Seems to be related to https://github.com/craftcms/cms/issues/4239

**Comment by jdsimcoe** [comment]
Wow, thanks @msiemens that's helpful to know it's not just me. Is there a way to fix this?

**Comment by msiemens** [comment]
For me a quick and dirty workaround was to comment out the `en_US.utf8` line from `vendor/craftcms/craft/bootstrap/web.php` (line 40 for me):

https://github.com/craftcms/cms/blob/6fe7ff045132db66a35c647eb8981556b3cd73e3/bootstrap/web.php#L34-L42

And clear the template caches after this change, of course 🙃

**Comment by jdsimcoe** [comment]
Thanks, @msiemens. Not sure how that would work on a site on Laravel Forge where deploys or `craft/cms` updates could wipe that out. Do you know if a long-term change is in the works?

**Comment by msiemens** [comment]
I've reported the issue on craftcms/cms but am waiting for an answer too

**Comment by chasegiunta** [comment]
I'm seeing this again on Craft 3.4.9 & PHP 7.3.13.

**Comment by jsunsawyer** [comment]
Having this issue come up on a recent project: Craft CMS 3.5.18 and PHP 7.3.22 (Using Valet)

**Comment by jsunsawyer** [comment]
I just got things working by setting `set_space_collapse` to `false` in my `typogrify.php` config file.

**Comment by romainpoirier** [comment]
Having the same issue using Typogrify 1.1.18 on Craft 3.6.4.1 and PHP 7.3.17 (MAMP).
Unfortunately, setting the `set_space_collapse` option to `false` does not fix this.

**Comment by khalwat** [comment]
Thx @jsunsawyer
