### ISSUE TITLE
Not displaying text after ,<br>

### ISSUE THREAD

**Issue by Coysh** [nystudio107/craft3-typogrify#37]
### Describe the bug
I have a redactor field that has the following text in it:
`<p>Test,<br>test,</p><p>test,<br>test,<br>test,</p><p>test</p>`

In my twig file I have the following:
```
{% set paragraphs = block.text | split('</p>') %}
{% for para in paragraphs %}
	{{ para | typogrify }}
{% endfor %}

```
Output is the below:
![image](https://user-images.githubusercontent.com/5764356/87559715-8ff68e80-c6b2-11ea-9adc-5850521d16de.png)

Or as HTML
```
<p>Test,<br></p>
<p>test,<br><br></p>
<p>test</p>
```

**Comment by khalwat** [comment]
This would be an issue for the core library: https://github.com/mundschenk-at/php-typography
