### ISSUE TITLE
BUG: Fuhrer will be changed to Führer

### ISSUE THREAD

**Issue by outline4** [nystudio107/craft3-typogrify#40]
### Bug

The name "Fuhrer" will be changed to "Führer". 

Of course in a German speaking part this sort of joke is not really funny. The poor Fuhrer must have heard this joke a zillion times, and now even the system is making fun of him 🗡️ 

Btw: it's even illegal to spell the word Führer in Germany. They had to change everything where the word Führer appeared. E.g. Stadtführer is not tolerated anymore. Führerausweis as well. The list goes on... It's a sensible word. 

How can I change this behavior?

### Versions
- Plugin version: 1.1.18
- Craft version: 3.4.26

**Comment by JayBox325** [comment]
TIL the word "Führer" is illegal in Germany! What an insane bug to find. 😂

**Comment by fthues** [comment]
I can assure you that the wort "Führer" is not illegal and never was! We carry Führerscheine, there are Stadtführer, Geschäftsführer and so on. But I can see how this bug could raise a few eyebrows. 🧐

**Comment by outline4** [comment]
> I can assure you that the wort "Führer" is not illegal and never was! We carry Führerscheine, there are Stadtführer, Geschäftsführer and so on. But I can see how this bug could raise a few eyebrows. 🧐

Of course you are right... 
https://de.wiktionary.org/wiki/Führer
"Zwar ist es nicht verboten, aber es ist teilweise wegen seiner dritten Bedeutung verpönt, das Wort ohne Präfix (Anführer, Reiseführer) zu benutzen."

This was a rather strange bug :)

**Comment by khalwat** [comment]
This would be an issue for the core library repo: https://github.com/mundschenk-at/php-typography

**Comment by mundschenk-at** [comment]
> This was a rather strange bug :)

It's not a bug, it's because you have Smart Diacritics enabled with the US English file (https://github.com/mundschenk-at/php-typography/blob/master/src/diacritics/en-US.json#L200).
