### ISSUE TITLE
Is there a way to disable just widow protection for a particular element?

### ISSUE THREAD

**Issue by architchandra** [nystudio107/craft3-typogrify#43]
Is there a way to disable just _widow protection_ for a particular element like there is the `isTtitle` parameter to disable hyphenation in titles/headings?

I want to disable widow protection on just one element, where the width is so little that widow protection looks worse (I want to continue using the `typogrify` filter for other functionality).

**Comment by khalwat** [comment]
Yep, you can do that as described here: https://nystudio107.com/docs/typogrify/#advanced-usage
