### ISSUE TITLE
Add support for setting the correct indefinite article or the past tense of a word

### ISSUE THREAD

**Issue by architchandra** [nystudio107/craft3-typogrify#44]
I need to use user-created labels in a sentence but the existing form does not fit properly. Also, I don't want website authors to need to set the past tense/singular/plural versions, etc.—too much work.

For example, if I have a label called _Rating_ and want to use it in a sentence/phrase like "X has been _rated_ by Y" or "X has been given _a_ rating by Y".

Currently, there is a filter to _singularize_. Any plans to take that a step further and add a way to set the correct indefinite article (a/an) based on the singularized word? Or even a filter to create the past tense for a word?

I am trying my best to frame the sentence/phrase in a way that works around having to use the past tense/indefinite articles but falling a little short.

**Comment by khalwat** [comment]
Typogrify leverages the built-in Yii2 Inflectors: https://www.yiiframework.com/doc/api/2.0/yii-helpers-inflector

Currently there's no support there for the a/an indefinite article unfortunately.
