### ISSUE TITLE
Is there a way to escape a set of characters when the |typogrify filter is applied?

### ISSUE THREAD

**Issue by architchandra** [nystudio107/craft3-typogrify#53]
In general, I want to have the functionality that Typogrify offers, but in certain situations, I want to use certain patterns liertally that would have otherwise been converted. eg. I want to use `(c)` in some cases without it getting converted to ©.

I couldn't find anything in the documentation that would help with this (usual escaping characters are not working). I even looked at the _php-typgraphy_ docs but no luck. Maybe I'm missing something obvious.

What should I do?

**Comment by khalwat** [comment]
I'm not really sure offhand, other than you could pass down a custom config in places where you wanted, ala: https://nystudio107.com/docs/typogrify/#advanced-usage

**Comment by mundschenk-at** [comment]
The canonical solution is to wrap the characters to be left alone in an "ignored" class, i.e. with `<span class="noTypo">` (based on the default configuration).
