### ISSUE TITLE
Widows filter

### ISSUE THREAD

**Issue by seandelaney** [nystudio107/craft3-typogrify#56]
### Widows/Widonts
Replaces the space between the last two words in a string with &nbsp;.

### Describe the solution you would like

{{ content|widont }}

Documentation suggests Widows are supported but when trying to call said filter, Twig error is thrown.

**Comment by khalwat** [comment]
The way to do this is:

```twig
{{ content |typogrify }}
```

Which will apply all of your settings (including widow protection):

https://nystudio107.com/docs/typogrify/#configuring-typogrify
