### ISSUE TITLE
Unintended hyphen-dash-replacement

### ISSUE THREAD

**Issue by animaux** [nystudio107/craft3-typogrify#67]
The german string `Kunst-, Kultur- und Architekturgeschichte` is rendered `Kunst–, Kultur- und Architekturgeschichte`, the first hyphen is replaced with an en-dash, but should remain a hyphen.

Plugin version: 1.1.19
Craft version: Craft Pro 3.7.34

**Comment by animaux** [comment]
Another example is the german spelling of email —> `E-Mail` which unintendedly becomes `E–Mail`.

**Comment by khalwat** [comment]
This is something that should probably be posted on the PHP Typography repository, as that's the library that does this:

https://github.com/mundschenk-at/php-typography/issues

**Comment by animaux** [comment]
I see, thanks!
