### ISSUE TITLE
UTF-Non-breaking-Space before Endash is replaced by regular space

### ISSUE THREAD

**Issue by animaux** [nystudio107/craft3-typogrify#68]
Typogrify seems to remove intentionally set non-breaking-spaces before en-dashes. We use them in order to prevent lines from starting with a dash, like this `[non-breaking-space][en-dash][regular-space]`.

With typogrify-filter:

![Bildschirmfoto 2022-03-07 um 11 30 18](https://user-images.githubusercontent.com/446874/157014408-58df4f63-ea61-4d2b-a108-e09cbf63ec3c.png)

Without typogrify-filter (intended behaviour):

![Bildschirmfoto 2022-03-07 um 11 30 35](https://user-images.githubusercontent.com/446874/157014486-d47fc1d1-756c-45ea-90c6-cda4e56f4a52.png)

Plugin version: 1.1.19
Craft version: Craft Pro 3.7.34

**Comment by khalwat** [comment]
Again, this is something that probably should be posted on the PHP Typography repository:

https://github.com/mundschenk-at/php-typography/issues

**Comment by animaux** [comment]
Thanks!

**Comment by animaux** [comment]
I feel this should be reopened as it can not be reproduced in a simple testcase using `php-typography` only. So the problem seems to arise somewhere else, please see: https://github.com/mundschenk-at/php-typography/issues/146#issuecomment-1061526565
