### ISSUE TITLE
Disable non-breaking hyphen-related formatting?

### ISSUE THREAD

**Issue by jasonmorehead** [nystudio107/craft3-typogrify#69]
As I understand it, the "php-typography" library [automatically converts hyphens to non-breaking hyphens](https://github.com/mundschenk-at/php-typography/issues/98) "in compound words when one part is very short (1 or 2 letters)." Which I understand is the ideal.

However, a website I'm working on uses a webfont that apparently doesn't have the "non-breaking hyphen" character. So whenever a word like "B-side" is used, that hyphen is converted into a non-breaking hyphen, and the word ends up looking something like "BXside." However, words like "mother-in-law" and "year-end" don't get converted to non-breaking hyphens and look just fine. 

Is there a way to disable the "non-breaking hyphen"-specific formatting altogether while leaving other hyphen-related formatting in place? (FWIW, the webfont in question supports en and em dashes.)

**Comment by khalwat** [comment]
This is something you'd probably need to as on the PHP Typography repo; all the Typogrify plugin does is pass these config values down to the PHP Typography library:

https://github.com/mundschenk-at/php-typography
