### ISSUE TITLE
"singularize()" calls "pluralize()" in the TypogrifyService

### ISSUE THREAD

**Issue by adampatpattison** [nystudio107/craft3-typogrify#7]
When using `singularize()` it is calling the `pluralize()` function from the Inflector Static Class.

 Lines 340 of the `/src/services/TypogrifyService.php` is currently:

```return abs($number) === 1 ? Inflector::pluralize($word) : $word;```

It should be:

```return abs($number) === 1 ? Inflector::singularize($word) : $word;```

**Comment by khalwat** [comment]
Ooops.

**Comment by khalwat** [comment]
Fixed in Version 1.1.9:

https://github.com/nystudio107/craft-typogrify/releases/tag/1.1.9
