### ISSUE TITLE
set_smart_diacritics is adding useless accented characters

### ISSUE THREAD

**Issue by romainpoirier** [nystudio107/craft3-typogrify#71]
### Describe the bug
`set_smart_diacritics` is adding accented characters where this makes absolutely no sense, making this option useless.
né doesn't means anything in French in a lot of context:

- Il est **né** → He is **born**
- Il **ne** veut **pas** → He does **not** want

While `ne` is most widely used, this setting is useless and must be disabled on French websites.

### To reproduce
Steps to reproduce the behaviour:
1. Enable Typogrify with `set_smart_diacritics` set to `true`
2. Write `ne`
3. See text converted to `né` on front-end

### Versions
- Plugin version: 1.1.19
- Craft version: 3.7.41

**Comment by khalwat** [comment]
This is unlikely to have anything to do with this plugin, and more likely an issue to take up with the PHP Typography library that it uses: https://github.com/mundschenk-at/php-typography
