### ISSUE TITLE
Allow empty Craft fields to be passed

### ISSUE THREAD

**Issue by rostockahoi** [nystudio107/craft3-typogrify#72]
### Describe the bug
Not necessarily a bug but it looks like the behaviour of all filters that accept a `$text` param has been changed after converting the plugin to v4, maybe with Rector?

Before v4 it was typeless and now it is `string $text`. When passing an empty Craft field (`null`) a TypeError is thrown.

### To reproduce
Steps to reproduce the behaviour:
1. Pass an empty field to the `typogrify` filter. (which is `null`)

### Expected behaviour
The filter should just return "nothing", like `null` or an empty string.

### Possible solutions
- omit type definition for the `$text` param
- extend type definition for the `$text` param to `string|int|float|null` (Don't know if `?string` would suffice due to type casting!?)
- set type definition to `mixed`

Any input on a possible solution?

### Versions
- Plugin version: 4
- Craft version: 4

**Comment by rostockahoi** [comment]
For reference the v1 code: https://github.com/nystudio107/craft-typogrify/blob/10e7da358c3ff46a8217ed9f714d504597897e76/src/services/TypogrifyService.php#L83

And v4: https://github.com/nystudio107/craft-typogrify/blob/2f91e05f450417a6ce9d801edbfb5478c06424b9/src/services/TypogrifyService.php#L83

**Comment by khalwat** [comment]
Fixed in 4.0.0 -> https://github.com/nystudio107/craft-typogrify/releases/tag/4.0.0
