### ISSUE TITLE
Possible to escape selectively?

### ISSUE THREAD

**Issue by dcplebranch** [nystudio107/craft3-typogrify#76]
### Question
I love the plugin. However, I'm having an issue where the term "Open 24/7" is being typogrified into a weird fraction thingy. Is there a way to typogrify everything except this select phrase? If there is a way to escape selectively, that would also work.

### Additional context
Typogrify 1.1.19
Craft 3.7.52

**Comment by khalwat** [comment]
Probably you could disable that setting here: https://github.com/nystudio107/craft-typogrify/blob/v1/src/config.php#L137

**Comment by dcplebranch** [comment]
@khalwat that would work except that setting is across the board. But I want other fractions to show as smart fractions, and only this one instance of 24/7 I want not to be shown that way. Is that possible?

**Comment by khalwat** [comment]
I'm not aware of a way to do that, no. You could ask over here tho: https://github.com/mundschenk-at/php-typography

That's the library the plugin uses.

**Comment by dcplebranch** [comment]
Thanks! I asked them and got a good answer. In case anyone else was wondering, here is a link to the answer: https://github.com/mundschenk-at/php-typography/issues/152#issuecomment-1256975891
