### ISSUE TITLE
Hyphenation cannot be set to false

### ISSUE THREAD

**Issue by nathansnelgrove** [nystudio107/craft3-typogrify#77]
### Describe the bug
When hyphenation is set to `false` in Typogrify.config, it still behaves as thought it were set to `true`.

### To reproduce
1. Copy and paste the config.php file to Craft's config folder. Rename the file typogrify.php
2. Set hyphenation to `false`

### Expected behaviour
I would expect hyphenation to disappear when using `{{ variableName | typogrify }}`, unless I am missing something.

### Screenshots
No screenshot, but a page in progress with the issue [can be previewed here](https://beta.donate.ehc.ca).

### Versions
- Plugin version: 1.1.19
- Craft version: 3.7.5.6

**Comment by khalwat** [comment]
All the Typgrify plugin does is pass these config values down to the PHP Typography library, so perhaps the issue is there:

https://github.com/mundschenk-at/php-typography
