### ISSUE TITLE
Headings + Hyphenation not working

### ISSUE THREAD

**Issue by Lennso** [nystudio107/craft3-typogrify#78]
I use typogrify with a redactor field:
`{{ entry.editor | typogrify }}`

My typogrify.php config:
```
"set_hyphenation" => true,
"set_hyphenate_headings" => true
```

My (german-text) html output:
```
<div>
<h6>Krank werden kann Jede:r</h6>
<h2>Warum brauche ich eine private Krankentagegeldversicherung?</h2>
<p>Die Krankentagegeld­&shy;versicherung schützt Sie gegen den Verdienstausfall bei Arbeits­&shy;unfähigkeit, soweit diese auf einer Krankheit oder einem Unfall beruht. Die Versicherung zahlt ab vereinbartem </p>
</div>
```

Hyphenation for my p-element is working, but not for the headings. 

Thank you for your help and thanks for the great plugin so far...

[typogrify.txt](https://github.com/nystudio107/craft-typogrify/files/9820270/typogrify.txt)

**Comment by khalwat** [comment]
So this is probably something you'd need to run by the core library author: https://github.com/mundschenk-at/php-typography/issues

**Comment by mundschenk-at** [comment]
Most likely this is caused by having dewidowing enabled.
