### ISSUE TITLE
set_smart_math setting shouldn't apply to dates

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft3-typogrify#8]
Easily fixed by setting to `false`, but thought it'd be worth noting anyway.

By default, typogrify filter will turn `04/09/18` into `04÷09÷18`.

**Comment by khalwat** [comment]
mmmmmmm. I guess it's not smart enough. I'd file the issue over here: https://github.com/mundschenk-at/php-typography

**Comment by mundschenk-at** [comment]
Should be fixed in `mundschenk-at/php-typography` 6.3.0.
