### ISSUE TITLE
Failed to install using CLI with --all flag

### ISSUE THREAD

**Issue by webrgp** [nystudio107/craft3-typogrify#82]
### Describe the bug
When trying to install all craft plugins at once using the `ddev craft plugin/install --all` command, I get this error:

```bash
*** installing typogrify
*** failed to install typogrify: Unable to register extension "nystudio107\typogrify\twigextensions\TypogrifyTwigExtension" as extensions have already been initialized.
```

### To reproduce
This only happens when running the command the first time, on a freshly installed craft site:
1. Install craft using `ddev composer create -y --no-scripts craftcms/craft`
2. Complete craft install in the cli using `ddev craft install/craft`
3. Composer require plugins:
```bash
ddev composer require --no-progress --no-scripts --no-interaction --optimize-autoloader --ignore-platform-reqs --with-all-dependencies craftcms/mailgun craftcms/redactor mmikkel/retcon nystudio107/craft-closure nystudio107/craft-retour nystudio107/craft-seomatic nystudio107/craft-typogrify nystudio107/craft-vite ostark/craft-relax putyourlightson/craft-blitz-recommendations sebastianlenz/linkfield spacecatninja/imager-x vaersaagod/dospaces verbb/formie verbb/navigation verbb/smith verbb/super-table
```
4. Install plugins `ddev craft plugin/install --all`

I only caught this because I use a Makefile to install a fresh copy of craft and those plugins and I notice this error only occurs AFTER I first run "composer require" to add the plugins. After running the `ddev craft plugin/install --all` the first time, I can run `ddev craft plugin/uninstall --all` and `ddev craft plugin/install --all` many times without an issue.

Not a big issue, just reporting ;-) Love this and all your other plugins!

### Versions
- Typogrify Plugin version: 4.0.1
- Craft version: 4.4.7.1

**Comment by khalwat** [comment]
This is not going to be an issue with the Typogrify plugin, but rather some plugin/module that loads before it, which is erroneously initializing Twig earlier than it should.

**Comment by webrgp** [comment]
Thanks for the tip! I don't mean to drag on this issue, but how would you recommend I track the culprit? Should I remove each other plugin one by one, except typography until it runs without the error? I will spend some time on it later tonight, but if you have another approach, or if you think I am missing something, please let me know.

Thanks again!

**Comment by khalwat** [comment]
It's laborious, but try uninstalling all plugins, then add them back in one by one until it happens.

**Comment by webrgp** [comment]
Ok, removed all except Typography, and added back one by one until it happened. Once I added SEOmatic, I got the error. To confirm this was just SEOmatic, I've re-added the rest and had no problem. Once I put SEOmatic into the mix, I got the error back.

I went ahead and I've added a few other plugins I commonly use to see if I run into similar issue with other plugins, and with SEOmatic in the mix, Sprig also errors with a similar message Typogrify outputs:

```bash
*** installing sprig
*** failed to install sprig: Unable to register extension "putyourlightson\sprig\twigextensions\SprigTwigExtension" as extensions have already been initialized.
```

And again, once I remove SEOmatic, both Typogrify, Sprig and the rest of the plugins installs without issues.

Just wanted to close the loop here, but now that I know that SEOmatic is related to this issue, do you want me to open it on the SEOmatic repo or should you do it? (I don't mind doing it)
