### ISSUE TITLE
French percentage formatting with no word wrap?

### ISSUE THREAD

**Issue by aaronrobb** [nystudio107/craft3-typogrify#83]
Is there a way to format French numbers so that the space that French use between the number and the percent symbol do not break on a line end?
Ie: In English we'd use "60%", but in French, it would look like "60 %", with a space.
In the odd change that the "60 %" falls at the end of a line, the % part could wrap to the next line. We're trying to prevent this from happening.

Any ideas?

**Comment by khalwat** [comment]
This is probably something to ask on the repository for the library that the Typogrify plugin uses:

https://github.com/mundschenk-at/php-typography

The Typogrify plugin exposes the full config for the PHP Typography library, so you can configure it as you please here:

https://github.com/nystudio107/craft-typogrify/blob/v1/src/config.php
