### ISSUE TITLE
Disabling Copyright Symbol

### ISSUE THREAD

**Issue by eclectiv** [nystudio107/craft3-typogrify#84]
### Question
Is there a way to disable (c) from turning into ©? Seems like this isn't available to disable in the config.php, namely because it's adopted by php-typography. Any guidance on the best way to disable the copyright symbol would be greatly appreciated!

**Comment by khalwat** [comment]
Yes, you can disable that via the `set_smart_marks` setting in the `config.php` -> https://github.com/nystudio107/craft-typogrify/blob/develop-v4/src/config.php#L128
