### ISSUE TITLE
Craft 5 Support

### ISSUE THREAD

**Issue by joelzerner** [nystudio107/craft3-typogrify#85]
Just checking to see if this plugin will be ported to Craft 5 and if so, what the timing is?

**Comment by khalwat** [comment]
Yep, it's next on my list. Should be done tomorrow

**Comment by CreateSean** [comment]
> Yep, it's next on my list. Should be done tomorrow

Sweet - this is the only plugin holding me back from updating my boilerplate.

**Comment by khalwat** [comment]
Typogrify `5.0.0-beta.1` released -> https://github.com/nystudio107/craft-typogrify/releases/tag/5.0.0-beta.1
