### ISSUE TITLE
Call to a member function getCallable() on null

### ISSUE THREAD

**Issue by adrianjean** [nystudio107/craft3-typogrify#86]
### Describe the bug
After upgrading to 4.0.2 on CraftCMS 4.8.6 Pro I get the following error:   `Call to a member function getCallable() on null`

Error:

```
Call to a member function getCallable() on null
1. in /srv/www/website.com/vendor/nystudio107/craft-typogrify/src/variables/TypogrifyVariable.phpat line 313
$text = '';
        }
        $text = (string)$text;
 
        $settings = Typogrify::$plugin->getSettings();
 
        if ($settings && $settings['default_escape'] === true) {
            $twig = Craft::$app->getView()->getTwig();
            $twig_escape_filter = $twig->getFilter('twig_escape_filter');
            $text = $twig_escape_filter->getCallable()($twig, $text);
        }
 
        return $text;
    }
}
```

### Versions
- Plugin version: 4.0.2
- Craft version: 4.8.6
- PHP 8.3.4
-

**Comment by khalwat** [comment]
I'm guessing your `config/typogrify.php` has: 

```php
    "default_escape" => true,
```

...in it?

**Comment by khalwat** [comment]
Addressed in the above commits. Released as `4.0.2` -> https://github.com/nystudio107/craft-typogrify/releases/tag/4.0.3

**Comment by adrianjean** [comment]
> I'm guessing your `config/typogrify.php` has:
> 
> ```
>     "default_escape" => true,
> ```
> 
> ...in it?

Yup!!

**Comment by adrianjean** [comment]
4.0.3 Fixed it — Thank you!!
